language: php

dist: trusty
sudo: false

git:
    depth: 1

matrix:
    include:
        - stage: legacy
          script: echo 'Legacy'
          php: 5.3
          dist: precise
          env:
            - PHP_COVERALLS_VERSION=v1.1.0
            - PHP_COVERALLS_SCRIPT=coveralls.phar
        - stage: current
          script: echo 'Current'
          php:
            - 5.6
            - 7.0
            - 7.1
            - 7.2
          env:
            - PHP_COVERALLS_VERSION=v2.1.0
            - PHP_COVERALLS_SCRIPT=php-coveralls.phar
        - stage: future
          script: echo 'Future'
          php: nightly
          env:
            - PHP_COVERALLS_VERSION=v2.1.0
            - PHP_COVERALLS_SCRIPT=php-coveralls.phar

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit

services:
    - memcached

before_install:
    - phpenv config-rm xdebug.ini
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    - composer install
    - ./vendor/bin/simple-phpunit install
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/$PHP_COVERALLS_VERSION/$PHP_COVERALLS_SCRIPT
    - chmod +x $PHP_COVERALS_SCRIPT
    - php $PHP_COVERALS_SCRIPT --version

before_script:
    - composer require doctrine/cache

script:
  - ./vendor/bin/simple-phpunit

after_script:
  - php $PHP_COVERALS_SCRIPT -v

#notifications:
#  slack:
#    rooms:
#      - piwik:3HWhNh21qPfDACQXTrJOb0mW#device-detector
#      - piwikpro:7OABSbDrywSTo2nv9lD2svXG
#
#  irc:
#    skip_join: true
#    on_success: change
#    channels:
#      - "irc.freenode.org#piwik-dev"
#    template:
#      - "%{repository} (%{commit}) : %{message} %{foo} "
#      - "Device Detector Build details: %{build_url}"
