language: php

dist: trusty
sudo: false

git:
    depth: 1

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

cache:
    directories:
        - $HOME/.composer/cache/files
        - .phpunit

env:
    global:
        - SYMFONY_PHPUNIT_DIR=.phpunit

services:
    - memcached

before_install:
    - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.3" ]]; then export PHP_COVERALS="v1.1.0"; else export PHP_COVERALS="v2.1.0"; fi
    - composer install
    - ./vendor/bin/simple-phpunit install
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/$(PHP_COVERALS)/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - php php-coveralls.phar --version

before_script:
    - composer require doctrine/cache

script:
  - ./vendor/bin/simple-phpunit

after_script:
  - php php-coveralls.phar -v

#notifications:
#  slack:
#    rooms:
#      - piwik:3HWhNh21qPfDACQXTrJOb0mW#device-detector
#      - piwikpro:7OABSbDrywSTo2nv9lD2svXG
#
#  irc:
#    skip_join: true
#    on_success: change
#    channels:
#      - "irc.freenode.org#piwik-dev"
#    template:
#      - "%{repository} (%{commit}) : %{message} %{foo} "
#      - "Device Detector Build details: %{build_url}"
