language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise

sudo: false

services:
  - memcached

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;'
  - (composer self-update; true)
  - composer require doctrine/cache ~1.2
  - composer install
  - ./vendor/bin/simple-phpunit install
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - php php-coveralls.phar --version

script:
  - ./vendor/bin/simple-phpunit

after_script:
  - php php-coveralls.phar -v

#notifications:
#  slack:
#    rooms:
#      - piwik:3HWhNh21qPfDACQXTrJOb0mW#device-detector
#      - piwikpro:7OABSbDrywSTo2nv9lD2svXG
#
#  irc:
#    skip_join: true
#    on_success: change
#    channels:
#      - "irc.freenode.org#piwik-dev"
#    template:
#      - "%{repository} (%{commit}) : %{message} %{foo} "
#      - "Device Detector Build details: %{build_url}"
